# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/hanz/Downloads/fdtd-New

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/hanz/Downloads/fdtd-New

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hanz/Downloads/fdtd-New/CMakeFiles /Users/hanz/Downloads/fdtd-New/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hanz/Downloads/fdtd-New/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fdtd

# Build rule for target.
fdtd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fdtd
.PHONY : fdtd

# fast build rule for target.
fdtd/fast:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/build
.PHONY : fdtd/fast

extern/config.o: extern/config.cpp.o

.PHONY : extern/config.o

# target to build an object file
extern/config.cpp.o:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/extern/config.cpp.o
.PHONY : extern/config.cpp.o

extern/config.i: extern/config.cpp.i

.PHONY : extern/config.i

# target to preprocess a source file
extern/config.cpp.i:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/extern/config.cpp.i
.PHONY : extern/config.cpp.i

extern/config.s: extern/config.cpp.s

.PHONY : extern/config.s

# target to generate assembly for a file
extern/config.cpp.s:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/extern/config.cpp.s
.PHONY : extern/config.cpp.s

extern/config_map.o: extern/config_map.cpp.o

.PHONY : extern/config_map.o

# target to build an object file
extern/config_map.cpp.o:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/extern/config_map.cpp.o
.PHONY : extern/config_map.cpp.o

extern/config_map.i: extern/config_map.cpp.i

.PHONY : extern/config_map.i

# target to preprocess a source file
extern/config_map.cpp.i:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/extern/config_map.cpp.i
.PHONY : extern/config_map.cpp.i

extern/config_map.s: extern/config_map.cpp.s

.PHONY : extern/config_map.s

# target to generate assembly for a file
extern/config_map.cpp.s:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/extern/config_map.cpp.s
.PHONY : extern/config_map.cpp.s

extern/lcfg_static.o: extern/lcfg_static.cpp.o

.PHONY : extern/lcfg_static.o

# target to build an object file
extern/lcfg_static.cpp.o:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/extern/lcfg_static.cpp.o
.PHONY : extern/lcfg_static.cpp.o

extern/lcfg_static.i: extern/lcfg_static.cpp.i

.PHONY : extern/lcfg_static.i

# target to preprocess a source file
extern/lcfg_static.cpp.i:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/extern/lcfg_static.cpp.i
.PHONY : extern/lcfg_static.cpp.i

extern/lcfg_static.s: extern/lcfg_static.cpp.s

.PHONY : extern/lcfg_static.s

# target to generate assembly for a file
extern/lcfg_static.cpp.s:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/extern/lcfg_static.cpp.s
.PHONY : extern/lcfg_static.cpp.s

src/chunk.o: src/chunk.cpp.o

.PHONY : src/chunk.o

# target to build an object file
src/chunk.cpp.o:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/src/chunk.cpp.o
.PHONY : src/chunk.cpp.o

src/chunk.i: src/chunk.cpp.i

.PHONY : src/chunk.i

# target to preprocess a source file
src/chunk.cpp.i:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/src/chunk.cpp.i
.PHONY : src/chunk.cpp.i

src/chunk.s: src/chunk.cpp.s

.PHONY : src/chunk.s

# target to generate assembly for a file
src/chunk.cpp.s:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/src/chunk.cpp.s
.PHONY : src/chunk.cpp.s

src/grid.o: src/grid.cpp.o

.PHONY : src/grid.o

# target to build an object file
src/grid.cpp.o:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/src/grid.cpp.o
.PHONY : src/grid.cpp.o

src/grid.i: src/grid.cpp.i

.PHONY : src/grid.i

# target to preprocess a source file
src/grid.cpp.i:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/src/grid.cpp.i
.PHONY : src/grid.cpp.i

src/grid.s: src/grid.cpp.s

.PHONY : src/grid.s

# target to generate assembly for a file
src/grid.cpp.s:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/src/grid.cpp.s
.PHONY : src/grid.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/params.o: src/params.cpp.o

.PHONY : src/params.o

# target to build an object file
src/params.cpp.o:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/src/params.cpp.o
.PHONY : src/params.cpp.o

src/params.i: src/params.cpp.i

.PHONY : src/params.i

# target to preprocess a source file
src/params.cpp.i:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/src/params.cpp.i
.PHONY : src/params.cpp.i

src/params.s: src/params.cpp.s

.PHONY : src/params.s

# target to generate assembly for a file
src/params.cpp.s:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/src/params.cpp.s
.PHONY : src/params.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... fdtd"
	@echo "... extern/config.o"
	@echo "... extern/config.i"
	@echo "... extern/config.s"
	@echo "... extern/config_map.o"
	@echo "... extern/config_map.i"
	@echo "... extern/config_map.s"
	@echo "... extern/lcfg_static.o"
	@echo "... extern/lcfg_static.i"
	@echo "... extern/lcfg_static.s"
	@echo "... src/chunk.o"
	@echo "... src/chunk.i"
	@echo "... src/chunk.s"
	@echo "... src/grid.o"
	@echo "... src/grid.i"
	@echo "... src/grid.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/params.o"
	@echo "... src/params.i"
	@echo "... src/params.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

